### PR TITLE
Add MPQ Replay Parser

### PR DESCRIPTION
**Pull request by eivindveg**
After much pain, frustration and wanting to do bad things to myself, we now have a parser that works.

This is a project that I want to extract to its own repositories(one parser, one exploder) in time, but so far, it only supports exactly what we need for HotSLogs.com pre-parsing. This allows us to ask HotSLogs.com if the replay should be uploaded, or if it's already present - should save a lot of bandwidth for users, and storage requests for @barrett777.

However; the MPQ extractor isn't that pretty. It's based on @darthdeus' [replaycruncher-client](https://github.com/darthdeus/replaycruncher-client), with lots of copy-pasta, and some of my "creative genius" mixed in.

As such; I hereby request an extensive code review from:
@TheCherry 
@ehatle 
@FredrickB 
@zhedar
@thorstenschaefer
@christianhood

I'm sorry for tagging so many of you for attention here, but I find it critical that the MPQ-extractor is as error free as possible for stability reasons. We don't want to leak memory, we don't want spontaneous exceptions.
The good part of this is that we now have the opportunity to finally bring a proper MPQ-extractor written in a high-level language to the table - all other implementations seem to be native.

### CODE REVIEW

**Comment by eivindveg** [comment]
Goddamnit; cannot integrate without changing the entire project structure. Will extract to new repositories immediately to save me a headache.

**Comment by eivindveg** [comment]
Pull request updated to use new artifact - present at https://github.com/eivindveg/HotSReplayParser

Will work on publishing Maven artifacts for these.

**Comment by zhedar** [comment]
That's great news. I wanted to work on this a while ago, but didn't really find where to begin with.  
I'm currently reviewing the mpqexploder logic and have some minor changes to discuss. The only problem with this is currently, that `Consumer<T>` doesn't support throwing checked exceptions, which would things look much smoother though.

**Comment by eivindveg** [comment]
While I understand all the "good points" of checked exceptions, they add a lot of catches, even for exceptions you should already have handled. I generally rethrow all checked exceptions as runtimeexceptions. See MpqException

**Comment by eivindveg** [comment]
Assuming we don't end up changing the API, this pull request should be fine as is.

**Pull request merged**
