### PR TITLE
adds installation instructions to readme

### PR DESCRIPTION
**Pull request by trosborn**
Hi,
It took me a few minute to find the install files for HotSUploader so I stuck a link to the release page in the readme. 

Also, apparently my text editor found two extraneous spaces..?

### CODE REVIEW

**Comment by zhedar** [comment]
We should probably also add a short brew installation note, also I thought we already did that.
I probably put those spaces there, because I normally use the original MarkDown, which needs you to put two spaces before line breaks. I'm not sure, but I seems GitHub flavoured MarkDown doesn't need them.

**Comment by zhedar** [comment]
I took a ]look at your rendered changes](https://github.com/trosborn/HotSUploader/blob/adds-install-instructions/README.md) and removing the two spaces actually results in the linebreak vanishing, so that's why I put it there ;)

**Comment by trosborn** [comment]
Ah, good to know. Apparently Sublime on my desktop is set to automatically delete trailing white spaces... I hadn't actually noticed the spaces were deleted until I made the PR. I put them back in.

Also, I added what I presume to be the brew command.

Let me know if anything else needs to be changed.

**Comment by zhedar** [comment]
I have some small notes to add, so I'm merging this now. Thanks for your help :)

**Pull request merged**
