### PR TITLE
Set current github version string dynamically

### PR DESCRIPTION
**Pull request by zhedar**
We probably should not set the current version string manually and read it from the manifest instead.

The only drawback would be, that this approach isn't properly testable anymore, `ReleaseManagerTest.testCurrentReleaseIsTheSameAsPomVersion()` will fail. 
That's because `getImplementationVersion()` will be set **after** the maven build and therefore won't be present at test time.

I also added a maven minimum version requirement, because the clean module needs atleast 3.0. This way `mvn versions:display-plugin-updates` will run without complaining.

I would like to discuss this, would you prefer the manual version due to testability?

### CODE REVIEW

**Comment by eivindveg** [comment]
The current tests exist to prevent accidental releases with wrong version string in the code:
If we were to update from version 1.3.1 to 2.0.0 without updating, users would get a notification to update even after they did update. This would undermine what little trust users have in this notification(I don't know). Therefore, this test maintains that you cannot build any native installer for the artifact without making sure the code reflects the version you're building.

I agree that this is a neat shortcut that avoids us setting duplicate flags; but that unit test really needs to pass. The failing unit test should be updated to parse the pom, and if it contains "-SNAPSHOT", should use the "Development" flag instead of the pom version. Since this is such an easy fix, I'll do that manually right now and integrate.

**Comment by eivindveg** [comment]
It doesn't seem to actually be possible to make this test pass. I'll do some testing on whether this works with a release. Expect more information "soon".

**Comment by zhedar** [comment]
The case you're describing can't happen with this fix though. So the need to test it isn't there anymore.

    if(pomVersion.endsWith("SNAPSHOT"))
            pomVersion = "Development";
would make this test pass though, but wouldn't really make sense, because at test time, the `currentVersion` will **always** be `Development`, as `getImplementationVersion()` returns null before the build. This also won't change with releases imo.

**Comment by eivindveg** [comment]
Agreed. Will do some testing to see how this holds up in a deployed bundle. If this works fine, it'll remove one check from the release check list.

**Pull request merged**
