### PR TITLE
Bugfix/preloader

### PR DESCRIPTION
**Pull request by eivindveg**
Not quite what I hoped to accomplish, but we can't change the style of the window to decorated after initially showing it. Therefore, we can't undecorate a single-stage preloader, then applying the normal layout to it afterwards before decorating it.

Let me know if this works any better, @zhedar?

### CODE REVIEW

**Comment by zhedar** [comment]
Sadly didn't change anything, still got that weird behaviour. It also seems independent from StageStyle and modality, so changing these doesn't affect it.

**Comment by eivindveg** [comment]
We could do away with the progress bar and just use a splash image. Looks less lively, but won't introduce any bugs apart from not displaying.

https://docs.oracle.com/javase/7/docs/api/java/awt/SplashScreen.html

**Comment by zhedar** [comment]
I already tested, if the used components were the problem and used an empty `Scene` and a single `Label` as well. Same problem. The components do not cause it, it's the presence of a second `Stage`.

**Comment by eivindveg** [comment]
Struggling with getting splash working using relative paths though. I'm sure no users want to create a file at "D:\Workspaces\HotSUploader\src\main\resources\images\hotsreplayuploader-large.png" just to get a splash screen. ;p

**Comment by eivindveg** [comment]
I seem to have doubly created the preloader - and also created it wrongly. The JavaFX Maven plugin adds the preloader to the manifest. Something I noticed while trying to get the splash working. Please try building 24a1a4f565393329ddb7e740f127986a9ce47a26 with `mvn clean package`. The preloader will not be active while running in an IDE, but that's fine.

**Comment by zhedar** [comment]
Still doesn't work. But due to the missing preloader, the problem doesn't appear in the jar anymore (although that won't help).  
Doesn't take the SplashScreen a simple URL? Doesn't `platformService.getLogoUrl() suffice?

**Comment by eivindveg** [comment]
The SplashScreen takes a JVM argument or a MANIFEST.MF attribute, so the platform services can't be used here. This is supposed to be really straight forward, but I cannot for the life of me get the splash screen displaying without an absolute url.

**Comment by eivindveg** [comment]
Out of curiousity though, if you close the stage, bring it back up, does the issue persist?

**Comment by eivindveg** [comment]
Closing this branch. Will look into splash or other behavioural fixes.

**Pull request closed without merging**
