### PR TITLE
Unofficial Linux version

### PR DESCRIPTION
**Pull request by TheCherry**

### CODE REVIEW

**Comment by eivindveg** [comment]
Hm. This is exactly why I don't want to officially support Linux when HotS doesn't. Seems somewhat hackish. Will see if I can integrate it fully into the controller code without detrimenting the current code.

**Comment by TheCherry** [comment]
That Browse bug is really annoying ... Had to google that problem, but that browse new method with the execute function works great. Will be nice if you pull it, so I can use the another versions instant.

**Comment by eivindveg** [comment]
I'll integrate it. Probably not as-is. Is replay detection functioning properly? I'm struggling to see how this deals with Wine paths.

**Comment by TheCherry** [comment]
Good question, did try to start a .StormReplay by double click, its start Hots but its says something like "the game missing files, to start the replay" (have a german version, can you tell the exact english error message later)

**Comment by eivindveg** [comment]
Please make sure this pull request contains functioning detection of replays before I can merge it.

**Comment by TheCherry** [comment]
What do mean exactly? That it's start a replay or do you mean "find and upload"? The upload work fine: https://img.bi/#/dMzW83G!lIPV4QPEPcxwVKgYAgWd_3zgMZqPsgbYdgggHw_p

**Comment by eivindveg** [comment]
Wow. I really wasn't expecting that to work correctly at all! Then yes, I'll make sure it can detect and integrate the Desktop browsing. Does this run under Wine or Java?

**Comment by TheCherry** [comment]
Its run under Java8, did start its with java -jar HotSLogs UploaderFX-jfx.jar

**Comment by eivindveg** [comment]
Aha. We'll have to build a jar-with-dependencies too. Does the JFX phase create any installers?

**Comment by TheCherry** [comment]
Yes its do, a .deb package, did try it, its install and work, have to try maybe that .deb package on a fresh installed Ubuntu. But the problem is that the java8 package isn’t in the main repository from Ubuntu: http://wiki.ubuntuusers.de/Java/Installation/Oracle_Java/Java_8

**Comment by eivindveg** [comment]
The .deb bundler will include a local version of the JRE.

**Comment by eivindveg** [comment]
Thanks. This pull request has been integrated manually.

**Comment by eivindveg** [comment]
Integrated into branch feature/wine-compat

**Comment by eivindveg** [comment]
Please build the latest commit from feature/wine-compat and install that .deb. Report back on the following:

* Browser actions work
* Uploading works
* FileHandler works when playing a match and a new replay should be autodetected

**Comment by TheCherry** [comment]
Nope its dont, first at all you forgot a SimpleHttpClient.encode in line 252
second, its seems that Desktop.isDesktopSupported() returns true and its try to do again the whole thing with desktop.browse( .... )

the rest should work still, see nothing in your comments what breaks it

**Comment by eivindveg** [comment]
Darn. That's what I wanted to avoid. Fix incoming

**Comment by eivindveg** [comment]
Try again please. =)

**Comment by TheCherry** [comment]
Yes now its work :+1: 
Can try the auto detect later too, but have the time to play now a game, but at last its worked before and you didn’t change anything

**Pull request closed without merging**
