### PR TITLE
Add parameter for overriding hots home directory

### PR DESCRIPTION
**Pull request by henrikolsson**
A feature suggestion. The default detection code does not work for me because I don't link "My Documents" in my wineprefix to my home directory.

This patch allows you to specify the directory manually through the command line with "-Dhots.home=...".

### CODE REVIEW

**Comment by eivindveg** [comment]
This looks like a reasonable request. Have you tested it for compatibility with native launchers or is this jar only?

Also, allow me to appreciate the irony of my project attracting the attention of the original JVM uploader that I actually based the original upload code on.

**Comment by minlexx** [comment]
The change looks harmless. May I ask @henrikolsson where do you link your "My Documents" to? Can it be detected automatically?

**Comment by henrikolsson** [comment]
@eivindveg Nope, I only tested it by building a jar. Well, your project has more features. My only goal with was to something working at all (and it was interesting to figure out how the original uploader worked).. :)

@minlexx I use a seperate wineprefix for each game and have the "My XYZ" directories in them as regular directories since i don't want to clutter up my normal files. I don't see a way of detecting this. It's probably not a very common use case.

Also perhaps an error message should be shown if the default detected directory does not exist?

**Comment by eivindveg** [comment]
There is no reason not to merge this as is. May be replaced with fully configurable settings at a later date.

**Comment by henrikolsson** [comment]
Great, thanks

**Pull request merged**
