### PR TITLE
Sort accounts by max last modified timestamp, resolves #118

### LINKED ISSUE #118: [Feature Request] Possibility to remove alts?
From time to time I played an alt way back with a friend to support his leveling without him getting enemys on my MMR. But since then the Players Dropdown Menu lists empty slots before I can select my main profile. Could you add a possibility to remove names from the dropdown menu or at least let me select which profile should be shown on startup? Thanks

### PR DESCRIPTION
**Pull request by rogusdev**

### CODE REVIEW

**Comment by eivindveg** [comment]
This is a simple, yet seemingly effective way to deal with this. I'll review this after my vacation. The plan is to allow users to set a default, but this will be a great deference for no set default. Thanks!

**Comment by eivindveg** [comment]
One note on your stream usages: I prefer a line break on every new segment of the stream. This produces a large amount of lines, but makes it very easy to see what happens.

**Comment by rogusdev** [comment]
Could you comment on the exact lines you wish to be new line separated?  Thanks.

**Comment by eivindveg** [comment]
The stream formatting I prefer is
```list.stream()
   .map(item -> item.toObject())
   .collect(someCollector());```

Ie one stream transformation per line. Sorry for bad examples. Currently roaming on my cell phone.

**Comment by rogusdev** [comment]
I pushed a commit earlier today that I believe should cover that to your tastes then.

**Comment by eivindveg** [comment]
Thank you for your contribution! This will be in for version 2.1! =)

**Comment by rogusdev** [comment]
Looking forward to it, glad to help!

**Pull request merged**
