### PR TITLE
Add Unranked Draft to list of MMR rankings.

### PR DESCRIPTION
**Pull request by mgius**

### CODE REVIEW

**Comment by mgius** [comment]
I didn't see any tests related to pulling these values out but I was able to run it locally with the main() in ClientTest.

**Comment by eivindveg** [comment]
Thanks a bunch! Will get develop cleaned up so we can get a green CI check for this! This will be in for 2.2.0.

**Comment by eivindveg** [comment]
Could you synchronize this branch with develop to retrigger a clean travis build?

**Comment by mgius** [comment]
@eivindveg Looks like it's good to go.

**Comment by eivindveg** [comment]
Thank you very much! This change will be part of the 2.2.0 release, and will be credited to you in the change notes. Feel free to add any relevant information you may want public in the contributors section of pom.xml and submitting a pull request.

**Pull request merged**
