### PR TITLE
Hotfix/2.0.3 Release

### PR DESCRIPTION
**Pull request by eivindveg**
Release pull request for version 2.0.3. Currently not complete; contains test failures.

Please review, @zhedar

### CODE REVIEW

**Comment by zhedar** [comment]
Will look into that tonight, so we can probably release tomorrow.

**Comment by zhedar** [comment]
The general changes look fine. I will test some tomorrow, but I don't expext any big problems.
What about the tests though, shouldn't they be included in 2.1 first?
Will add some OSX related paths, but post 2.0.3 probably.

**Comment by eivindveg** [comment]
Keep in mind the tests must pass before we can merge. Especially the test for the failed upload issue.

**Comment by eivindveg** [comment]
Creating release notes and signing off once I've tested that my specific case is fixed.

**Pull request merged**
